#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <random>
#include <iterator>
#include <cstring>
#include <chrono>
#include <map>
#include <cmath>
#include <typeinfo>
#include <functional>
#include <memory>
#include <csignal>
#include <tuple>
#include <cstdio>
#include <sstream>
#include <ctime>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\algorithm\string.hpp>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\any.hpp>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\bimap.hpp>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\signals2.hpp>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\msm\back\state_machine.hpp>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\msm\front\state_machine_def.hpp>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\msm\front\functor_row.hpp>
