#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <random>
#include <iterator>
#include <cstring>
#include <chrono>
#include <map>
#include <cmath>
#include <typeinfo>
#include <functional>
#include <memory>
#include <csignal>
#include <tuple>
#include <cstdio>	 
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\algorithm\string.hpp>
#include <sstream>